[tool.poetry]
name = "leakix"
version = "0.1.0"
description = "Client to LeakIX API"
authors = ["Danny Willems <danny@leakix.net>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "*"
l9format = "^1.3.1"

[tool.poetry.dev-dependencies]
python-decouple = "*"
pytest = "*"
black = "*"
mypy = "*"
requests-mock = "*"
pylint = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
