name: CI
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        poetry-version: ["1.4.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry==${{ matrix.poetry-version}}
      - name: View poetry --help
        run: poetry --help
      - name: Install deps
        run: poetry install
      - name: Run tests
        run: poetry run pytest tests
      - name: Run black
        run: poetry run black leakix/*.py tests/*.py example/*.py --check
      - name: Security audit
        if: matrix.python-version != '3.7'
        run: poetry run pip-audit
