name: CI
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        poetry-version: ["2.3.1"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry==${{ matrix.poetry-version}}
      - name: View poetry --help
        run: poetry --help
      - name: Install deps
        run: poetry install
      - name: Run tests
        run: poetry run pytest tests
      - name: Check formatting
        run: poetry run ruff format --check leakix/ tests/ example/ executable/
      - name: Run linter
        run: poetry run ruff check leakix/ tests/ example/ executable/
      - name: Security audit
        run: poetry run pip-audit
